In [2]:
import sklearn.model_selection
import torch 
import torch.nn as nn
import torch.optim as optim

import sklearn
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
n_samples = 1000
X,y = make_circles(n_samples,noise=0.03,random_state=42)

circles = pd.DataFrame({"X1": X[:,0], 
                        "X2":X[:,1], 
                        "Label": y})
circles.head(50)
#plt.scatter(X[:,0],X[:,1], c=y, cmap=plt.cm.RdYlBu)

# viewing samples of features and labels
#print(f"X sample--> {X[0]} \n y sample--> {y[0]}")

X = torch.from_numpy(X).type(torch.float) 
y = torch.from_numpy(y).type(torch.float)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                    random_state=42)
y_train.shape

torch.Size([800])

In [33]:
class CircleModel(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        
        self.network  =  nn.Sequential(
            nn.Linear(2,5),
            nn.Linear(5,1)            
            )
    
    def forward(self,x):
        return self.network(x)
    


        
        

In [34]:
Model = CircleModel()
Model.state_dict()

OrderedDict([('network.0.weight',
              tensor([[ 0.6786, -0.0236],
                      [ 0.0363, -0.3325],
                      [ 0.4100, -0.1866],
                      [-0.6575,  0.2433],
                      [ 0.4353,  0.2191]])),
             ('network.0.bias',
              tensor([ 0.6705, -0.2467, -0.1985,  0.3917,  0.1183])),
             ('network.1.weight',
              tensor([[-0.0808, -0.0069,  0.4396, -0.2364, -0.3674]])),
             ('network.1.bias', tensor([-0.3274]))])

In [44]:
with torch.inference_mode():
    u_pred = Model(X_train)
print(f"{u_pred.shape}-----{y_train.shape}")
u_pred == y_train
print(torch.round(u_pred[:10]))
print(u_pred[:10])

torch.Size([800, 1])-----torch.Size([800])
tensor([[-0.],
        [-0.],
        [-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.],
        [-0.]])
tensor([[-0.4235],
        [-0.3684],
        [-0.6981],
        [-0.6711],
        [-0.7958],
        [-0.6088],
        [-0.8002],
        [-0.6417],
        [-0.8424],
        [-0.3849]])
